<a href="https://colab.research.google.com/github/FilipeDellaPorta/analise-de-dados/blob/main/Pandas_transformacao_e_manipulacao_de_dados_desafios.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [124]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

#Desafio: trabalhando em outros contextos

Chegou a hora de pôr em prática tudo o que aprendemos durante as aulas. Preparei dois projetos extras para desenvolvermos durante o curso, para garantir que possamos praticar bastante! Para isso, vamos trabalhar com 2 novos conjuntos de dados, mas que dessa vez serão bem menores. As bases de dados estão disponíveis para download abaixo:

*   Projeto desafio 1: vendas online - [dados_vendas_clientes.json](https://cdn3.gnarususercontent.com.br/2928-transformacao-manipulacao-dados/dados_vendas_clientes.json);
*   Projeto desafio 2: administração de condomínios - [dados_locacao_imoveis.json](https://cdn3.gnarususercontent.com.br/2928-transformacao-manipulacao-dados/dados_locacao_imoveis.json).

Em cada aula, desenvolveremos uma etapa dos projetos. Portanto, salve seu código de construção em cada desafio para que possa aplicá-lo nos desafios posteriores.

##Etapa 1

*   Projeto desafio 1: vendas online

O objetivo desse projeto é realizar uma análise dos resultados de um evento com os clientes de uma empresa de vendas online. Foi coletado um conjunto de dados que contém os clientes que mais gastaram com produtos dentro de 5 dias de vendas, que é o período de duração do evento. Essa análise vai identificar o cliente com a maior compra na semana, que irá receber um prêmio da loja, e posteriormente, ela pode ajudar a empresa a criar novas estratégias para atrair mais clientes.

A base de dados utilizada nessa análise é a dados_vendas_clientes.json e contém informações importantes sobre os clientes como, o nome de cadastro do cliente, o valor total pago na compra e o dia da compra.

Sabendo essas informações, o desafio do projeto 1: vendas online será abrir a base de dados com Pandas e aplicar o json_normalize.

*   Projeto desafio 2: administração de condomínios

A administração de condomínios é uma tarefa que requer muita atenção e organização. Entre as diversas responsabilidades da gestão está o recebimento dos aluguéis dos locatários. Para garantir uma boa saúde financeira do empreendimento, é fundamental que esses pagamentos sejam feitos de forma regular e pontual. No entanto, sabemos que nem sempre isso acontece.

Pensando nisso, proponho um desafio de tratamento de dados com o objetivo de analisar o atraso no pagamento de aluguéis no condomínio de alguns moradores. Disponibilizo a base de dados dados_locacao_imoveis.json, que contém informações sobre o apartamento dos locatários, o dia acordado para o pagamento do aluguel, o dia da efetivação do pagamento de aluguel e o valor do aluguel.

Com essas informações, o desafio do projeto 2: administração de condomínios será similar ao desafio do projeto 1, abrir a base de dados com Pandas e aplicar o json_normalize no DataFrame.

In [125]:
import pandas as pd

In [126]:
dados_vendas_clientes = pd.read_json('/content/drive/MyDrive/Colab Notebooks/dados_vendas_clientes.json')
dados_vendas_clientes

                                        dados_vendas
0  {'Data de venda': '06/06/2022', 'Cliente': ['@...
1  {'Data de venda': '07/06/2022', 'Cliente': ['I...
2  {'Data de venda': '08/06/2022', 'Cliente': ['I...
3  {'Data de venda': '09/06/2022', 'Cliente': ['J...
4  {'Data de venda': '10/06/2022', 'Cliente': ['M...

In [127]:
dados_vendas_clientes_normalizados = pd.json_normalize(dados_vendas_clientes['dados_vendas'])
dados_vendas_clientes_normalizados.head()

,Data de venda,Cliente,Valor da compra
0,06/06/2022,"[@ANA _LUCIA 321, DieGO ARMANDIU 210, DieGO AR...","[R$ 836,5, R$ 573,33, R$ 392,8, R$ 512,34]"
1,07/06/2022,"[Isabely JOanes 738, Isabely JOanes 738, Isabe...","[R$ 825,31, R$ 168,07, R$ 339,18, R$ 314,69]"
2,08/06/2022,"[Isabely JOanes 738, JOãO Gabriel 671, Julya m...","[R$ 682,05, R$ 386,34, R$ 622,65, R$ 630,79]"
3,09/06/2022,"[Julya meireles 914, MaRIA Julia 444, MaRIA Ju...","[R$ 390,3, R$ 759,16, R$ 334,47, R$ 678,78]"
4,10/06/2022,"[MaRIA Julia 444, PEDRO PASCO 812, Paulo castr...","[R$ 314,24, R$ 311,15, R$ 899,16, R$ 885,24]"

In [128]:
dados_locacao_imoveis = pd.read_json('/content/drive/MyDrive/Colab Notebooks/dados_locacao_imoveis.json')
dados_locacao_imoveis

                                        dados_locacao
0   {'apartamento': 'A101 (blocoAP)', 'datas_combi...
1   {'apartamento': 'A102 (blocoAP)', 'datas_combi...
2   {'apartamento': 'B201 (blocoAP)', 'datas_combi...
3   {'apartamento': 'B202 (blocoAP)', 'datas_combi...
4   {'apartamento': 'C301 (blocoAP)', 'datas_combi...
5   {'apartamento': 'C302 (blocoAP)', 'datas_combi...
6   {'apartamento': 'D401 (blocoAP)', 'datas_combi...
7   {'apartamento': 'D402 (blocoAP)', 'datas_combi...
8   {'apartamento': 'E501 (blocoAP)', 'datas_combi...
9   {'apartamento': 'E502 (blocoAP)', 'datas_combi...
10  {'apartamento': 'F601 (blocoAP)', 'datas_combi...
11  {'apartamento': 'F602 (blocoAP)', 'datas_combi...
12  {'apartamento': 'G701 (blocoAP)', 'datas_combi...
13  {'apartamento': 'G702 (blocoAP)', 'datas_combi...
14  {'apartamento': 'H801 (blocoAP)', 'datas_combi...

In [129]:
dados_locacao_imoveis_normalizados = pd.json_normalize(dados_locacao_imoveis['dados_locacao'])
dados_locacao_imoveis_normalizados.head()

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),"[01/06/2022, 01/07/2022]","[05/06/2022, 03/07/2022]","[$ 1000,0 reais, $ 2500,0 reais]"
1,A102 (blocoAP),"[02/06/2022, 02/07/2022]","[02/06/2022, 06/07/2022]","[$ 1100,0 reais, $ 2600,0 reais]"
2,B201 (blocoAP),"[03/06/2022, 03/07/2022]","[07/06/2022, 03/07/2022]","[$ 1200,0 reais, $ 2700,0 reais]"
3,B202 (blocoAP),"[04/06/2022, 04/07/2022]","[07/06/2022, 05/07/2022]","[$ 1300,0 reais, $ 2800,0 reais]"
4,C301 (blocoAP),"[05/06/2022, 05/07/2022]","[10/06/2022, 09/07/2022]","[$ 1400,0 reais, $ 2900,0 reais]"

##Etapa 2

*   **Projeto desafio 1: vendas online**

Lemos a base de dados no desafio anterior, agora podemos avançar nas transformações desses dados. Então, o novo desafio do projeto 1 será dividido em algumas metas:

*   Remover os dados em listas dentro do DataFrame;
*   Verificar os tipos de dados;
*   Identificar colunas numéricas;
*   Transformar a coluna numérica para o tipo numérico.

In [130]:
dados_vendas_clientes_normalizados

,Data de venda,Cliente,Valor da compra
0,06/06/2022,"[@ANA _LUCIA 321, DieGO ARMANDIU 210, DieGO AR...","[R$ 836,5, R$ 573,33, R$ 392,8, R$ 512,34]"
1,07/06/2022,"[Isabely JOanes 738, Isabely JOanes 738, Isabe...","[R$ 825,31, R$ 168,07, R$ 339,18, R$ 314,69]"
2,08/06/2022,"[Isabely JOanes 738, JOãO Gabriel 671, Julya m...","[R$ 682,05, R$ 386,34, R$ 622,65, R$ 630,79]"
3,09/06/2022,"[Julya meireles 914, MaRIA Julia 444, MaRIA Ju...","[R$ 390,3, R$ 759,16, R$ 334,47, R$ 678,78]"
4,10/06/2022,"[MaRIA Julia 444, PEDRO PASCO 812, Paulo castr...","[R$ 314,24, R$ 311,15, R$ 899,16, R$ 885,24]"

In [131]:
colunas_vendas_clientes = list(dados_vendas_clientes_normalizados.columns)
colunas_vendas_clientes

['Data de venda', 'Cliente', 'Valor da compra']

In [132]:
dados_vendas_clientes_explodidos = dados_vendas_clientes_normalizados.explode(colunas_vendas_clientes[1:])
dados_vendas_clientes_explodidos.head()

  Data de venda             Cliente Valor da compra
0    06/06/2022     @ANA _LUCIA 321        R$ 836,5
0    06/06/2022  DieGO ARMANDIU 210       R$ 573,33
0    06/06/2022  DieGO ARMANDIU 210        R$ 392,8
0    06/06/2022  DieGO ARMANDIU 210       R$ 512,34
1    07/06/2022  Isabely JOanes 738       R$ 825,31

In [133]:
dados_vendas_clientes_explodidos.reset_index(inplace=True, drop=True)
dados_vendas_clientes_explodidos.head()

  Data de venda             Cliente Valor da compra
0    06/06/2022     @ANA _LUCIA 321        R$ 836,5
1    06/06/2022  DieGO ARMANDIU 210       R$ 573,33
2    06/06/2022  DieGO ARMANDIU 210        R$ 392,8
3    06/06/2022  DieGO ARMANDIU 210       R$ 512,34
4    07/06/2022  Isabely JOanes 738       R$ 825,31

In [134]:
dados_vendas_clientes_explodidos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     object
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     object
dtypes: object(3)
memory usage: 612.0+ bytes

In [135]:
import numpy as np

In [136]:
dados_vendas_clientes_explodidos['Valor da compra'] = dados_vendas_clientes_explodidos['Valor da compra'].apply(lambda x : x.replace('R$', '').replace(',', '').strip()).astype(np.float64)
dados_vendas_clientes = dados_vendas_clientes_explodidos
dados_vendas_clientes['Valor da compra']

0      8365.0
1     57333.0
2      3928.0
3     51234.0
4     82531.0
5     16807.0
6     33918.0
7     31469.0
8     68205.0
9     38634.0
10    62265.0
11    63079.0
12     3903.0
13    75916.0
14    33447.0
15    67878.0
16    31424.0
17    31115.0
18    89916.0
19    88524.0
Name: Valor da compra, dtype: float64

In [137]:
dados_vendas_clientes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     object
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     float64
dtypes: float64(1), object(2)
memory usage: 612.0+ bytes

*   **Projeto desafio 2: administração de condomínios**

Lemos a base de dados no desafio anterior, agora podemos avançar nas transformações desses dados. Então, da mesma forma que o projeto 1, o desafio do projeto 2 está listado em algumas metas:

*   Remover os dados em listas dentro do DataFrame;
*   Verificar os tipos de dados;
*   Identificar colunas numéricas;
*   Transformar a coluna numérica para o tipo numérico.

In [138]:
dados_locacao_imoveis_normalizados.head()

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),"[01/06/2022, 01/07/2022]","[05/06/2022, 03/07/2022]","[$ 1000,0 reais, $ 2500,0 reais]"
1,A102 (blocoAP),"[02/06/2022, 02/07/2022]","[02/06/2022, 06/07/2022]","[$ 1100,0 reais, $ 2600,0 reais]"
2,B201 (blocoAP),"[03/06/2022, 03/07/2022]","[07/06/2022, 03/07/2022]","[$ 1200,0 reais, $ 2700,0 reais]"
3,B202 (blocoAP),"[04/06/2022, 04/07/2022]","[07/06/2022, 05/07/2022]","[$ 1300,0 reais, $ 2800,0 reais]"
4,C301 (blocoAP),"[05/06/2022, 05/07/2022]","[10/06/2022, 09/07/2022]","[$ 1400,0 reais, $ 2900,0 reais]"

In [139]:
colunas_locacao_imoveis = list(dados_locacao_imoveis_normalizados.columns)
colunas_locacao_imoveis

['apartamento',
 'datas_combinadas_pagamento',
 'datas_de_pagamento',
 'valor_aluguel']

In [140]:
dados_locacao_imoveis_explodidos = dados_locacao_imoveis_normalizados.explode(colunas_locacao_imoveis[1:])
dados_locacao_imoveis_explodidos.head()

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),01/06/2022,05/06/2022,"$ 1000,0 reais"
0,A101 (blocoAP),01/07/2022,03/07/2022,"$ 2500,0 reais"
1,A102 (blocoAP),02/06/2022,02/06/2022,"$ 1100,0 reais"
1,A102 (blocoAP),02/07/2022,06/07/2022,"$ 2600,0 reais"
2,B201 (blocoAP),03/06/2022,07/06/2022,"$ 1200,0 reais"

In [141]:
dados_locacao_imoveis_explodidos['valor_aluguel'] = dados_locacao_imoveis_explodidos['valor_aluguel'].apply(lambda x : x.replace('$', '').replace(',', '.').replace('reais', '').strip())
dados_locacao_imoveis_explodidos['valor_aluguel']

0     1000.0
0     2500.0
1     1100.0
1     2600.0
2     1200.0
2     2700.0
3     1300.0
3     2800.0
4     1400.0
4     2900.0
5     1500.0
5     1200.0
6     1600.0
6     1300.0
7     1700.0
7     1400.0
8     1800.0
8     1500.0
9     1900.0
9     1600.0
10    2000.0
10    1000.0
11    2100.0
11    1100.0
12    2200.0
12    1200.0
13    2300.0
13    2100.0
14    2400.0
14    2200.0
Name: valor_aluguel, dtype: object

In [142]:
import numpy as np

In [143]:
dados_locacao_imoveis_explodidos['valor_aluguel'] = dados_locacao_imoveis_explodidos['valor_aluguel'].astype(np.float64)
dados_locacao_imoveis_explodidos.reset_index(inplace=True, drop=True)
dados_locacao_imoveis = dados_locacao_imoveis_explodidos
dados_locacao_imoveis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     object
 2   datas_de_pagamento          30 non-null     object
 3   valor_aluguel               30 non-null     float64
dtypes: float64(1), object(3)
memory usage: 1.1+ KB

In [144]:
dados_locacao_imoveis.head()

      apartamento datas_combinadas_pagamento datas_de_pagamento  valor_aluguel
0  A101 (blocoAP)                 01/06/2022         05/06/2022         1000.0
1  A101 (blocoAP)                 01/07/2022         03/07/2022         2500.0
2  A102 (blocoAP)                 02/06/2022         02/06/2022         1100.0
3  A102 (blocoAP)                 02/07/2022         06/07/2022         2600.0
4  B201 (blocoAP)                 03/06/2022         07/06/2022         1200.0

#Desafio: trabalhando em outros contextos
##Etapa 3

*   **Projeto desafio 1: vendas online**

**Na etapa 2,** trabalhamos na transformação dos dados numéricos. Agora, podemos trabalhar com valores textuais.

Devido a uma instabilidade no site da empresa, tivemos problemas com os nomes dos clientes durante o salvamento. Isso resultou em uma coluna de nomes de clientes com uma mistura de letras, maiúsculas e minúsculas, números e outros caracteres.

Sabendo disso, manipule os textos presentes na coluna `Cliente` para que seja obtido como resultado os nomes dos clientes em letras minúsculas, com a ausência de caracteres especiais ou números.

In [148]:
dados_vendas_clientes['Cliente'] = dados_vendas_clientes['Cliente'].str.lower().replace('[0-9\W_]', ' ', regex=True) #ou poderia fazer a negativa assim [^a-z ]
dados_vendas_clientes['Cliente']

0         ana  lucia
1     diego armandiu
2     diego armandiu
3     diego armandiu
4     isabely joanes
5     isabely joanes
6     isabely joanes
7     isabely joanes
8     isabely joanes
9       joão gabriel
10    julya meireles
11    julya meireles
12    julya meireles
13       maria julia
14       maria julia
15       maria julia
16       maria julia
17       pedro pasco
18      paulo castro
19     thiago fritzz
Name: Cliente, dtype: object

*   **Projeto desafio 2: administração de condomínios**

**Na etapa 2**, trabalhamos na transformação dos dados numéricos. Agora, podemos trabalhar com valores textuais.

Buscando explicar a organização da identificação dos apartamentos, durante a criação do conjunto de dados, foi adicionado o texto `(blocoAP)`. Esse texto informa que os nomes dos apartamentos estão organizados com a letra do bloco seguida do número do apartamento. No entanto, isso não traz nenhuma informação para nossos dados, sendo interessante realizar a remoção desse texto no conjunto de dados.

Com isso, manipule os textos na coluna `apartamento` para remover o texto `(blocoAP)` do DataFrame.

In [150]:
dados_locacao_imoveis['apartamento'] = dados_locacao_imoveis['apartamento'].str.replace(' (blocoAP)', '')
dados_locacao_imoveis['apartamento']

0     A101
1     A101
2     A102
3     A102
4     B201
5     B201
6     B202
7     B202
8     C301
9     C301
10    C302
11    C302
12    D401
13    D401
14    D402
15    D402
16    E501
17    E501
18    E502
19    E502
20    F601
21    F601
22    F602
23    F602
24    G701
25    G701
26    G702
27    G702
28    H801
29    H801
Name: apartamento, dtype: object

##Etapa 4


*   **Projeto desafio 1: vendas online**

Nas etapas anteriores, já trabalhamos com vários tipos de dados, agora podemos trabalhar com os dados de tempo.

Na coluna `Data de venda`, temos datas em formato 'dia/mês/ano' (`dd/mm/AAAA`). Transforme esses dados para o tipo datetime e busque uma forma de visualização de subconjunto que possa contribuir no objetivo do contexto que os dados estão inseridos.

Se você não lembra o problema do projeto desafio 1, vou deixar abaixo o texto da situação para facilitar o encontro da informação:


**O objetivo desse projeto é realizar uma análise dos resultados de um evento com os clientes de uma empresa de vendas online. Foi coletado um conjunto de dados que contém os clientes que mais gastaram com produtos dentro de 5 dias de vendas, que é o período de duração do evento. Essa análise vai identificar o cliente com a maior compra na semana, que irá receber um prêmio da loja, e posteriormente, ela pode ajudar a empresa a criar novas estratégias para atrair mais clientes.**

In [168]:
dados_vendas_clientes['Data de venda'] = pd.to_datetime(dados_vendas_clientes['Data de venda'], format='%d/%m/%Y')
dados_vendas_clientes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     datetime64[ns]
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     float64
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 612.0+ bytes

In [172]:
dados_vendas_clientes

   Data de venda             Cliente  Valor da compra
0     2022-06-06      ana  lucia               8365.0
1     2022-06-06  diego armandiu              57333.0
2     2022-06-06  diego armandiu               3928.0
3     2022-06-06  diego armandiu              51234.0
4     2022-07-06  isabely joanes              82531.0
5     2022-07-06  isabely joanes              16807.0
6     2022-07-06  isabely joanes              33918.0
7     2022-07-06  isabely joanes              31469.0
8     2022-08-06  isabely joanes              68205.0
9     2022-08-06    joão gabriel              38634.0
10    2022-08-06  julya meireles              62265.0
11    2022-08-06  julya meireles              63079.0
12    2022-09-06  julya meireles               3903.0
13    2022-09-06     maria julia              75916.0
14    2022-09-06     maria julia              33447.0
15    2022-09-06     maria julia              67878.0
16    2022-10-06     maria julia              31424.0
17    2022-10-06     pedro pasco              31115.0
18    2022-10-06    paulo castro              89916.0
19    2022-10-06   thiago fritzz              88524.0

In [171]:
total_compras = dados_vendas_clientes.groupby(['Cliente'])['Valor da compra'].sum()
total_compras

Cliente
 ana  lucia             8365.0
diego armandiu        112495.0
isabely joanes        232930.0
joão gabriel           38634.0
julya meireles        129247.0
maria julia           208665.0
paulo castro           89916.0
pedro pasco            31115.0
thiago fritzz          88524.0
Name: Valor da compra, dtype: float64

*   **Projeto desafio 2: administração de condomínios**

Assim como no projeto desafio 1, trabalhamos com todas as colunas exceto as que envolvem datas.

Nas colunas `datas_de_pagamento` e `datas_combinadas_pagamento`, temos datas em formato 'dia/mês/ano' (`dd/mm/AAAA`). Transforme esses dados para o tipo datetime e busque uma forma de visualização de subconjunto que possa contribuir no objetivo do contexto que os dados estão inseridos.

Se você não lembra o problema do projeto desafio 2, vou deixar abaixo o texto da situação para facilitar o encontro da informação:


**A administração de condomínios é uma tarefa que requer muita atenção e organização. Entre as diversas responsabilidades da gestão está o recebimento dos aluguéis dos locatários. Para garantir uma boa saúde financeira do empreendimento, é fundamental que esses pagamentos sejam feitos de forma regular e pontual. No entanto, sabemos que nem sempre isso acontece. Pensando nisso, proponho um desafio de tratamento de dados com o objetivo de analisar o atraso no pagamento de aluguéis no condomínio fictício de alguns moradores.**

In [174]:
dados_locacao_imoveis.head()

  apartamento datas_combinadas_pagamento datas_de_pagamento  valor_aluguel
0        A101                 01/06/2022         05/06/2022         1000.0
1        A101                 01/07/2022         03/07/2022         2500.0
2        A102                 02/06/2022         02/06/2022         1100.0
3        A102                 02/07/2022         06/07/2022         2600.0
4        B201                 03/06/2022         07/06/2022         1200.0

In [175]:
dados_locacao_imoveis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     object
 2   datas_de_pagamento          30 non-null     object
 3   valor_aluguel               30 non-null     float64
dtypes: float64(1), object(3)
memory usage: 1.1+ KB

In [186]:
dados_locacao_imoveis['datas_combinadas_pagamento'] = pd.to_datetime(dados_locacao_imoveis['datas_combinadas_pagamento'], dayfirst=True)
dados_locacao_imoveis['datas_de_pagamento'] = pd.to_datetime(dados_locacao_imoveis['datas_de_pagamento'], dayfirst=True)

In [187]:
dados_locacao_imoveis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     datetime64[ns]
 2   datas_de_pagamento          30 non-null     datetime64[ns]
 3   valor_aluguel               30 non-null     float64
dtypes: datetime64[ns](2), float64(1), object(1)
memory usage: 1.1+ KB

In [202]:
dados_locacao_imoveis['atrasos'] = dados_locacao_imoveis['datas_de_pagamento'] > dados_locacao_imoveis['datas_combinadas_pagamento']

In [195]:
dados_locacao_imoveis

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel,atrasados
0,A101,2022-06-01,2022-06-05,1000.0,True
1,A101,2022-07-01,2022-07-03,2500.0,True
2,A102,2022-06-02,2022-06-02,1100.0,False
3,A102,2022-07-02,2022-07-06,2600.0,True
4,B201,2022-06-03,2022-06-07,1200.0,True
5,B201,2022-07-03,2022-07-03,2700.0,False
6,B202,2022-06-04,2022-06-07,1300.0,True
7,B202,2022-07-04,2022-07-05,2800.0,True
8,C301,2022-06-05,2022-06-10,1400.0,True
9,C301,2022-07-05,2022-07-09,2900.0,True
10,C302,2022-06-06,2022-06-08,1500.0,True
11,C302,2022-07-06,2022-07-12,1200.0,True
12,D401,2022-06-07,2022-06-07,1600.0,False
13,D401,2022-07-07,2022-07-09,1300.0,True
14,D402,2022-06-08,2022-06-10,1700.0,True
15,D402,2022-07-08,2022-07-14,1400.0,True
16,E501,2022-06-09,2022-06-10,1800.0,True
17,E501,2022-07-09,2022-07-09,1500.0,False
18,E502,2022-06-10,2022-06-16,1900.0,True
19,E502,2022-07-10,2022-07-12,1600.0,True
20,F601,2022-06-11,2022-06-17,2000.0,True
21,F601,2022-07-11,2022-07-13,1000.0,True
22,F602,2022-06-12,2022-06-15,2100.0,True
23,F602,2022-07-12,2022-07-12,1100.0,False
24,G701,2022-06-13,2022-06-19,2200.0,True
25,G701,2022-07-13,2022-07-20,1200.0,True
26,G702,2022-06-14,2022-06-15,2300.0,True
27,G702,2022-07-14,2022-07-17,2100.0,True
28,H801,2022-06-15,2022-06-18,2400.0,True
29,H801,2022-07-15,2022-07-16,2200.0,True



```
# Transformar para o tipo datetime definindo o formato de data como DD/MM/AAAA ('%d/%m/%Y')
dados['datas_combinadas_pagamento'] = pd.to_datetime(dados['datas_combinadas_pagamento'], format='%d/%m/%Y')
dados['datas_de_pagamento'] = pd.to_datetime(dados['datas_de_pagamento'], format='%d/%m/%Y')

# Visualizar o resultado
dados

# Para contribuir na solução do contexto é possível calcular a diferença de dias
# entre a data combinada e a data de pagamento com dt.days
dados['atraso'] = (dados['datas_de_pagamento'] - dados['datas_combinadas_pagamento']).dt.days

# Observar o novo DataFrame
dados

# Calcular a média de tempo de atraso por apartamentos
media_atraso = dados.groupby(['apartamento'])['atraso'].mean()

# Visualizar o resultado
media_atraso
```

In [199]:
dados_locacao_imoveis['atrasados'] = (dados_locacao_imoveis['datas_de_pagamento'] - dados_locacao_imoveis['datas_combinadas_pagamento']).dt.days

In [200]:
media_atraso = dados_locacao_imoveis.groupby(['apartamento'])['atrasados'].mean()
media_atraso

apartamento
A101    3.0
A102    2.0
B201    2.0
B202    2.0
C301    4.5
C302    4.0
D401    1.0
D402    4.0
E501    0.5
E502    4.0
F601    4.0
F602    1.5
G701    6.5
G702    2.0
H801    2.0
Name: atrasados, dtype: float64

In [203]:
dados_locacao_imoveis

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel,atrasados,atrasos
0,A101,2022-06-01,2022-06-05,1000.0,4,True
1,A101,2022-07-01,2022-07-03,2500.0,2,True
2,A102,2022-06-02,2022-06-02,1100.0,0,False
3,A102,2022-07-02,2022-07-06,2600.0,4,True
4,B201,2022-06-03,2022-06-07,1200.0,4,True
5,B201,2022-07-03,2022-07-03,2700.0,0,False
6,B202,2022-06-04,2022-06-07,1300.0,3,True
7,B202,2022-07-04,2022-07-05,2800.0,1,True
8,C301,2022-06-05,2022-06-10,1400.0,5,True
9,C301,2022-07-05,2022-07-09,2900.0,4,True
10,C302,2022-06-06,2022-06-08,1500.0,2,True
11,C302,2022-07-06,2022-07-12,1200.0,6,True
12,D401,2022-06-07,2022-06-07,1600.0,0,False
13,D401,2022-07-07,2022-07-09,1300.0,2,True
14,D402,2022-06-08,2022-06-10,1700.0,2,True
15,D402,2022-07-08,2022-07-14,1400.0,6,True
16,E501,2022-06-09,2022-06-10,1800.0,1,True
17,E501,2022-07-09,2022-07-09,1500.0,0,False
18,E502,2022-06-10,2022-06-16,1900.0,6,True
19,E502,2022-07-10,2022-07-12,1600.0,2,True
20,F601,2022-06-11,2022-06-17,2000.0,6,True
21,F601,2022-07-11,2022-07-13,1000.0,2,True
22,F602,2022-06-12,2022-06-15,2100.0,3,True
23,F602,2022-07-12,2022-07-12,1100.0,0,False
24,G701,2022-06-13,2022-06-19,2200.0,6,True
25,G701,2022-07-13,2022-07-20,1200.0,7,True
26,G702,2022-06-14,2022-06-15,2300.0,1,True
27,G702,2022-07-14,2022-07-17,2100.0,3,True
28,H801,2022-06-15,2022-06-18,2400.0,3,True
29,H801,2022-07-15,2022-07-16,2200.0,1,True